spring.application.name=mmo-server
spring.datasource.url=jdbc:mysql://localhost:3306/mmo
spring.datasource.username=root
spring.datasource.password=Dhruv@1234!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true